/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    education: Education;
    experience: Experience;
    'blog-sources': BlogSource;
    socials: Social;
    'sponsor-tiers': SponsorTier;
    testimonials: Testimonial;
    certificates: Certificate;
    sponsors: Sponsor;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    education: EducationSelect<false> | EducationSelect<true>;
    experience: ExperienceSelect<false> | ExperienceSelect<true>;
    'blog-sources': BlogSourcesSelect<false> | BlogSourcesSelect<true>;
    socials: SocialsSelect<false> | SocialsSelect<true>;
    'sponsor-tiers': SponsorTiersSelect<false> | SponsorTiersSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    certificates: CertificatesSelect<false> | CertificatesSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homePage: HomePage;
    aboutPage: AboutPage;
    projectsPage: ProjectsPage;
    servicesPage: ServicesPage;
    sponsorsPage: SponsorsPage;
    blogsPage: BlogsPage;
    videosPage: VideosPage;
    testimonialsPage: TestimonialsPage;
    contactSection: ContactSection;
    navbar: Navbar;
    footer: Footer;
    analytics: Analytics;
    siteSettings: SiteSetting;
  };
  globalsSelect: {
    homePage: HomePageSelect<false> | HomePageSelect<true>;
    aboutPage: AboutPageSelect<false> | AboutPageSelect<true>;
    projectsPage: ProjectsPageSelect<false> | ProjectsPageSelect<true>;
    servicesPage: ServicesPageSelect<false> | ServicesPageSelect<true>;
    sponsorsPage: SponsorsPageSelect<false> | SponsorsPageSelect<true>;
    blogsPage: BlogsPageSelect<false> | BlogsPageSelect<true>;
    videosPage: VideosPageSelect<false> | VideosPageSelect<true>;
    testimonialsPage: TestimonialsPageSelect<false> | TestimonialsPageSelect<true>;
    contactSection: ContactSectionSelect<false> | ContactSectionSelect<true>;
    navbar: NavbarSelect<false> | NavbarSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    analytics: AnalyticsSelect<false> | AnalyticsSelect<true>;
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    username: string;
  };
  login: {
    password: string;
    username: string;
  };
  registerFirstUser: {
    password: string;
    username: string;
  };
  unlock: {
    username: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email?: string | null;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  blurhash?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  slug: string;
  title: string;
  description: string;
  icon: string;
  features: {
    feature: string;
    id?: string | null;
  }[];
  deliverables: {
    step: number;
    title: string;
    description: string;
    icon: string;
    details: {
      detail: string;
      id?: string | null;
    }[];
    duration: string;
    cost: string;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education".
 */
export interface Education {
  id: number;
  title: string;
  university: string;
  period: string;
  description: string;
  location: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience".
 */
export interface Experience {
  id: number;
  title: string;
  company: string;
  period: string;
  location: string;
  responsibilities: {
    responsibility: string;
    id?: string | null;
  }[];
  skills: string[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-sources".
 */
export interface BlogSource {
  id: number;
  source: 'medium' | 'custom';
  url?: string | null;
  username?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socials".
 */
export interface Social {
  id: number;
  platform: 'facebook' | 'x' | 'instagram' | 'linkedin' | 'github' | 'youtube';
  url: string;
  ariaLabel: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsor-tiers".
 */
export interface SponsorTier {
  id: number;
  name: string;
  slug: string;
  description: string;
  price: number;
  benefits: {
    benefit: string;
    id?: string | null;
  }[];
  tierUrl: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  title: string;
  company: string;
  image: number | Media;
  testimonial: string;
  category: 'client' | 'general' | 'colleague';
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates".
 */
export interface Certificate {
  id: number;
  title: string;
  issuer: string;
  issued: string;
  verifyUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  name: string;
  avatar: number | Media;
  url: string;
  tier: number | SponsorTier;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'education';
        value: number | Education;
      } | null)
    | ({
        relationTo: 'experience';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'blog-sources';
        value: number | BlogSource;
      } | null)
    | ({
        relationTo: 'socials';
        value: number | Social;
      } | null)
    | ({
        relationTo: 'sponsor-tiers';
        value: number | SponsorTier;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'certificates';
        value: number | Certificate;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  blurhash?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  icon?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  deliverables?:
    | T
    | {
        step?: T;
        title?: T;
        description?: T;
        icon?: T;
        details?:
          | T
          | {
              detail?: T;
              id?: T;
            };
        duration?: T;
        cost?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education_select".
 */
export interface EducationSelect<T extends boolean = true> {
  title?: T;
  university?: T;
  period?: T;
  description?: T;
  location?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience_select".
 */
export interface ExperienceSelect<T extends boolean = true> {
  title?: T;
  company?: T;
  period?: T;
  location?: T;
  responsibilities?:
    | T
    | {
        responsibility?: T;
        id?: T;
      };
  skills?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-sources_select".
 */
export interface BlogSourcesSelect<T extends boolean = true> {
  source?: T;
  url?: T;
  username?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socials_select".
 */
export interface SocialsSelect<T extends boolean = true> {
  platform?: T;
  url?: T;
  ariaLabel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsor-tiers_select".
 */
export interface SponsorTiersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  price?: T;
  benefits?:
    | T
    | {
        benefit?: T;
        id?: T;
      };
  tierUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  company?: T;
  image?: T;
  testimonial?: T;
  category?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates_select".
 */
export interface CertificatesSelect<T extends boolean = true> {
  title?: T;
  issuer?: T;
  issued?: T;
  verifyUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  url?: T;
  tier?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage".
 */
export interface HomePage {
  id: number;
  heroSection: {
    name: string;
    typingTexts: string[];
    typingDelay?: number | null;
    bio: string;
    primary?:
      | {
          icon?: string | null;
          label: string;
          url: string;
          visible?: boolean | null;
          id?: string | null;
          blockName?: string | null;
          blockType: 'button';
        }[]
      | null;
    secondary?:
      | {
          icon?: string | null;
          label: string;
          url: string;
          visible?: boolean | null;
          id?: string | null;
          blockName?: string | null;
          blockType: 'button';
        }[]
      | null;
    profileImage: {
      src: number | Media;
      alt: string;
      id?: string | null;
      blockName?: string | null;
      blockType: 'image';
    }[];
  };
  projectSection: {
    title: string;
    description: string;
    projectUrls: {
      url: string;
      id?: string | null;
    }[];
    allProjectsButton?:
      | {
          icon?: string | null;
          label: string;
          url: string;
          visible?: boolean | null;
          id?: string | null;
          blockName?: string | null;
          blockType: 'button';
        }[]
      | null;
  };
  serviceSection: {
    title: string;
    description: string;
    allServicesButton?:
      | {
          icon?: string | null;
          label: string;
          url: string;
          visible?: boolean | null;
          id?: string | null;
          blockName?: string | null;
          blockType: 'button';
        }[]
      | null;
    bookCallButton?:
      | {
          icon?: string | null;
          label: string;
          url: string;
          visible?: boolean | null;
          id?: string | null;
          blockName?: string | null;
          blockType: 'button';
        }[]
      | null;
  };
  blogSection: {
    title: string;
    description: string;
    viewAllButton?:
      | {
          icon?: string | null;
          label: string;
          url: string;
          visible?: boolean | null;
          id?: string | null;
          blockName?: string | null;
          blockType: 'button';
        }[]
      | null;
  };
  videoSection: {
    title: string;
    description: string;
    channelUrl: string;
    channelId: string;
    viewAllButton?:
      | {
          icon?: string | null;
          label: string;
          url: string;
          visible?: boolean | null;
          id?: string | null;
          blockName?: string | null;
          blockType: 'button';
        }[]
      | null;
  };
  testimonialSection: {
    title: string;
    description: string;
    viewAllButton?:
      | {
          icon?: string | null;
          label: string;
          url: string;
          visible?: boolean | null;
          id?: string | null;
          blockName?: string | null;
          blockType: 'button';
        }[]
      | null;
  };
  sponsorSection: {
    title: string;
    description: string;
    viewAllButton?:
      | {
          icon?: string | null;
          label: string;
          url: string;
          visible?: boolean | null;
          id?: string | null;
          blockName?: string | null;
          blockType: 'button';
        }[]
      | null;
  };
  seo: {
    keywords: string[];
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutPage".
 */
export interface AboutPage {
  id: number;
  name: string;
  title: string;
  aboutImage: {
    src: number | Media;
    alt: string;
    id?: string | null;
    blockName?: string | null;
    blockType: 'image';
  }[];
  description: {
    desc: string;
    id?: string | null;
  }[];
  coreValues: {
    label: string;
    value: string;
    id?: string | null;
  }[];
  skills: string[];
  seo: {
    keywords: string[];
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projectsPage".
 */
export interface ProjectsPage {
  id: number;
  title: string;
  description: string;
  seo: {
    keywords: string[];
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicesPage".
 */
export interface ServicesPage {
  id: number;
  title: string;
  description: string;
  seo: {
    keywords: string[];
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsorsPage".
 */
export interface SponsorsPage {
  id: number;
  title: string;
  description: string;
  seo: {
    keywords: string[];
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogsPage".
 */
export interface BlogsPage {
  id: number;
  title: string;
  description: string;
  seo: {
    keywords: string[];
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videosPage".
 */
export interface VideosPage {
  id: number;
  title: string;
  description: string;
  seo: {
    keywords: string[];
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonialsPage".
 */
export interface TestimonialsPage {
  id: number;
  title: string;
  description: string;
  seo: {
    keywords: string[];
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactSection".
 */
export interface ContactSection {
  id: number;
  title: string;
  description: string;
  email: string;
  reasons?:
    | {
        name: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar".
 */
export interface Navbar {
  id: number;
  logo: {
    lightLogo: number | Media;
    darkLogo: number | Media;
  };
  navItems?:
    | {
        label: string;
        url: string;
        icon: string;
        hasSubmenu?: boolean | null;
        visible?: boolean | null;
        subNavItems?:
          | {
              label: string;
              url: string;
              icon: string;
              description?: string | null;
              visible?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  buyButton?:
    | {
        icon?: string | null;
        label: string;
        url: string;
        visible?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'button';
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  logo: {
    lightLogo: number | Media;
    darkLogo: number | Media;
  };
  socialSection: {
    title: string;
  };
  categories?:
    | {
        title: string;
        items?:
          | {
              label: string;
              url: string;
              visible?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  copyrightText: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics".
 */
export interface Analytics {
  id: number;
  googleAnalyticsId: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * Use %s where the page title should be inserted.
   */
  titleTemplate: string;
  defaultLanguage: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroSection?:
    | T
    | {
        name?: T;
        typingTexts?: T;
        typingDelay?: T;
        bio?: T;
        primary?:
          | T
          | {
              button?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    url?: T;
                    visible?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
        secondary?:
          | T
          | {
              button?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    url?: T;
                    visible?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
        profileImage?:
          | T
          | {
              image?:
                | T
                | {
                    src?: T;
                    alt?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  projectSection?:
    | T
    | {
        title?: T;
        description?: T;
        projectUrls?:
          | T
          | {
              url?: T;
              id?: T;
            };
        allProjectsButton?:
          | T
          | {
              button?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    url?: T;
                    visible?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  serviceSection?:
    | T
    | {
        title?: T;
        description?: T;
        allServicesButton?:
          | T
          | {
              button?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    url?: T;
                    visible?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
        bookCallButton?:
          | T
          | {
              button?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    url?: T;
                    visible?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  blogSection?:
    | T
    | {
        title?: T;
        description?: T;
        viewAllButton?:
          | T
          | {
              button?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    url?: T;
                    visible?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  videoSection?:
    | T
    | {
        title?: T;
        description?: T;
        channelUrl?: T;
        channelId?: T;
        viewAllButton?:
          | T
          | {
              button?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    url?: T;
                    visible?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  testimonialSection?:
    | T
    | {
        title?: T;
        description?: T;
        viewAllButton?:
          | T
          | {
              button?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    url?: T;
                    visible?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  sponsorSection?:
    | T
    | {
        title?: T;
        description?: T;
        viewAllButton?:
          | T
          | {
              button?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    url?: T;
                    visible?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  seo?:
    | T
    | {
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutPage_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  aboutImage?:
    | T
    | {
        image?:
          | T
          | {
              src?: T;
              alt?: T;
              id?: T;
              blockName?: T;
            };
      };
  description?:
    | T
    | {
        desc?: T;
        id?: T;
      };
  coreValues?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  skills?: T;
  seo?:
    | T
    | {
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projectsPage_select".
 */
export interface ProjectsPageSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  seo?:
    | T
    | {
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicesPage_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  seo?:
    | T
    | {
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsorsPage_select".
 */
export interface SponsorsPageSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  seo?:
    | T
    | {
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogsPage_select".
 */
export interface BlogsPageSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  seo?:
    | T
    | {
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videosPage_select".
 */
export interface VideosPageSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  seo?:
    | T
    | {
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonialsPage_select".
 */
export interface TestimonialsPageSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  seo?:
    | T
    | {
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactSection_select".
 */
export interface ContactSectionSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  email?: T;
  reasons?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar_select".
 */
export interface NavbarSelect<T extends boolean = true> {
  logo?:
    | T
    | {
        lightLogo?: T;
        darkLogo?: T;
      };
  navItems?:
    | T
    | {
        label?: T;
        url?: T;
        icon?: T;
        hasSubmenu?: T;
        visible?: T;
        subNavItems?:
          | T
          | {
              label?: T;
              url?: T;
              icon?: T;
              description?: T;
              visible?: T;
              id?: T;
            };
        id?: T;
      };
  buyButton?:
    | T
    | {
        button?:
          | T
          | {
              icon?: T;
              label?: T;
              url?: T;
              visible?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?:
    | T
    | {
        lightLogo?: T;
        darkLogo?: T;
      };
  socialSection?:
    | T
    | {
        title?: T;
      };
  categories?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              label?: T;
              url?: T;
              visible?: T;
              id?: T;
            };
        id?: T;
      };
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics_select".
 */
export interface AnalyticsSelect<T extends boolean = true> {
  googleAnalyticsId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  titleTemplate?: T;
  defaultLanguage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}